apiVersion: apps/v1
kind: Deployment 
metadata:
  name: pf-deployment
  labels:
    app: pf
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pf
  template:
    metadata:
      labels:
        app: pf
    spec:
      containers:
        - name: pf-cont
          image: yashpatil1678/portfolio:latest
          ports:
            - containerPort: 80



---
apiVersion: v1
kind: Service
metadata:
  name: pf-svc
spec:
  type: NodePort
  selector:
    app: pf
  ports:
    - port: 80
      nodePort: 30001
    

